---
title: "Data wrangling"
output: html_document
---

```{r}
library(tidyverse) #
install.packages("tidyverse")
```



```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

##inspect the data set 
str(gapminder)
head(gapminder)
###Can specify the number you want using ,
tail(gapminder)
summary(gapminder)

install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #####Name of columns
####ncol, nrow numbers of columns and rows respectively
####can reverse-engineer dim using c for nrow and ncol
```

###Dplyr
Result is a new data frame. 

```{r}
###filter by rows 
filter(gapminder, lifeExp<29)
filter(gapminder, country =="Mexico")
filter(gapminder, country %in% c("Mexico","Peru"))
filter(gapminder, country == "Mexico", year==2002)

sweden<-filter(gapminder, country=="Sweden")
mean(sweden$lifeExp)

#####Select by columns
select(gapminder, year, lifeExp)
#select without columns
select(gapminder, -continent)

gap_cambodia<- filter(gapminder, country =="Cambodia")
gap_cambodia2<- select(gap_cambodia, -continent, -lifeExp)

```

The pipe operator will change my life.

```{r}
gapminder%>% head()
####equ. of head(gapminder), can add 3 in the () to get the number of rows you want

##ctr, shift, m shortcut for %>% 
gap_cambodia<- gapminder%>% filter(country =="Cambodia") %>% select( -continent, -lifeExp)


```

Mutate adds new variables
```{r}
gapminder %>% 
  mutate(index=1:nrow(gapminder))

gapminder %>% 
  mutate(planet="Earth")

gapminder %>% 
  mutate(gdp=pop*gdpPercap)

max_gdp<-gapminder %>% filter(country %in% c("Egypt", "Vietnam")) %>%mutate(gdp=pop*gdpPercap) %>% mutate(max.gdp=max(gdp))
max_gdp

#same as
max_gdp<-gapminder %>% filter(country %in% c("Egypt", "Vietnam")) %>%mutate(gdp=pop*gdpPercap,max.gdp=max(gdp))

```

##Group by
Allows you to do the same operation over all your sites
cmdz undo
```{r}
gap_grouped <-gapminder %>% group_by(country) %>%mutate(gdp=pop*gdpPercap,max.gdp=max(gdp)) %>% ungroup()
View(gap_grouped)

#Summarise
gap_summarise<-gapminder %>%  group_by(country) %>% mutate(gdp=pop*gdpPercap) %>% summarise(max_gdp=max(gdp)) %>%  ungroup()
View(gap_summarise)
```
Summarise with group by

#####Arrange columns

```{r}
##Arrange by max gdp, desc() gives descending order
gap_summarise<-gapminder %>%  group_by(country) %>% mutate(gdp=pop*gdpPercap) %>% summarise(max_gdp=max(gdp)) %>%  ungroup() %>% arrange(desc(max_gdp))
```

E.g.
*dplyr*::select shows what package the function comes from.

##Joining data

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

####
co2 %>% head()

#####Creating a new gapminder variable with only 2007 data
gap_2007<- gapminder %>% filter(year==2007)
###142 observations (countries)

###Left join, by -what you want to join the datasets by. 
lj<- left_join(gap_2007, co2, by="country")
###See if the number of observations matches what you expect
#Could alternatively use %>% 

####Right join
rj<- right_join(gap_2007, co2)
#If you don't specify it will choose a column that have identical names, better to say which one you want.
#Left_joins may be easier to link into a chain of code. 
#Need to consider which one you use if you refer to the column not by name but position.
```





